services:
  frontend:
    image: ghcr.io/noppakorn/asr-project/web:2023-05-15
    container_name: noodle-shop-web
    ports:
      - "3000:3000"

  api:
    image: ghcr.io/noppakorn/asr-project/api:2023-05-15
    container_name: noodle-shop-api
    ports:
      - "8000:8000"
